language: node_js
node_js:
  - "stable"
addons: chrome
chrome: 
  - "stable"
sauce_connect:
    username: "Tcoco4"
    jwt:
    secure: "The secure string output by `travis encrypt SAUCE_ACCESS_KEY=d15a3bab-781f-4d02-8bcd-aff84a2cd5fa`"
install:
    - npm install
    - npm install -g @ionic/cli
before_script:
- npm install -g @angular/cli
script: 
 - ng test
#- echo $ npm run test
